declare const styles: {
    praeventionTimeplaner: string;
    container: string;
    header: string;
    section: string;
    'form-group': string;
    btn: string;
    'team-grid': string;
    'team-member': string;
    gender: string;
    male: string;
    female: string;
    results: string;
    'appointment-slot': string;
    'appointment-details': string;
    alert: string;
    info: string;
    success: string;
    warning: string;
    loading: string;
    'time-slot-grid': string;
    'time-slot': string;
    selected: string;
    'two-column': string;
};
export default styles;
